/**
 * WebUSB thermal printer utility.
 *
 * Usage:
 *   1. Call setupPrinter() once to request USB permission and pair the device.
 *   2. Call printTicket(data) after each successful sale.
 *
 * No npm packages required — uses the browser's native navigator.usb API
 * and the ESC/POS bytes generated by $lib/ticket.ts.
 */

import { generateTicket, generateComanda } from '$lib/ticket.js';
import type { ComandaData } from '$lib/ticket.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface PrintTicketData {
	businessName?: string;
	orderId: number;
	items: { nombre: string; cantidad: number; precioUnitario: string }[];
	total: string;
	metodoPago: string;
	vendedor: string;
	fecha: Date;
}

// ─── Module-level USB state ───────────────────────────────────────────────────
// Survives component re-renders; one device per browser session.

let device: USBDevice | null = null;

/**
 * Returns true when a USB device has been paired and is open.
 */
export function isPrinterConnected(): boolean {
	return device !== null && device.opened;
}

// ─── Setup ────────────────────────────────────────────────────────────────────

/**
 * Opens the browser USB device picker, pairs the selected device, and stores
 * it for later use.  Throws a user-friendly string on failure.
 */
export async function setupPrinter(): Promise<USBDevice> {
	if (!navigator.usb) {
		throw new Error('WebUSB no está disponible en este navegador. Usa Chrome o Edge.');
	}

	try {
		const selected = await navigator.usb.requestDevice({ filters: [] });

		// If we already had a device open, close it first
		if (device && device.opened) {
			try {
				await device.close();
			} catch {
				// ignore
			}
		}

		await selected.open();

		if (selected.configuration === null) {
			await selected.selectConfiguration(1);
		}

		// Try to claim interface 0; some printers use a different interface number.
		// We attempt 0 first and fall back to the first available interface.
		try {
			await selected.claimInterface(0);
		} catch {
			const firstIface = selected.configuration?.interfaces[0]?.interfaceNumber;
			if (firstIface !== undefined) {
				await selected.claimInterface(firstIface);
			} else {
				throw new Error('No se pudo reclamar ninguna interfaz USB de la impresora.');
			}
		}

		device = selected;
		return device;
	} catch (err: unknown) {
		// User cancelled the picker
		if (err instanceof DOMException && err.name === 'NotFoundError') {
			throw new Error('No se seleccionó ninguna impresora.');
		}
		// Re-throw descriptive errors
		if (err instanceof Error) throw err;
		throw new Error('Error desconocido al conectar la impresora.');
	}
}

// ─── Print ─────────────────────────────────────────────────────────────────────

/**
 * Finds the first bulk-OUT endpoint on the claimed interface and returns its
 * endpoint number.  Throws if none is found.
 */
function getOutEndpoint(usbDevice: USBDevice): number {
	for (const iface of usbDevice.configuration?.interfaces ?? []) {
		for (const alt of iface.alternates) {
			for (const ep of alt.endpoints) {
				if (ep.direction === 'out' && ep.type === 'bulk') {
					return ep.endpointNumber;
				}
			}
		}
	}
	throw new Error('No se encontró un endpoint de salida en la impresora USB.');
}

/**
 * Generates the ticket bytes and sends them to the paired USB printer.
 * Throws a user-friendly string if the printer is not configured.
 */
export async function printTicket(data: PrintTicketData): Promise<void> {
	if (!device || !device.opened) {
		throw new Error('Impresora no configurada. Usa "Configurar Impresora" primero.');
	}

	const buffer = generateTicket(data);
	const endpointNumber = getOutEndpoint(device);

	const result = await device.transferOut(endpointNumber, buffer);

	if (result.status !== 'ok') {
		throw new Error(`Error al enviar datos a la impresora (status: ${result.status}).`);
	}
}

/**
 * Generates a kitchen/bar comanda and sends it to the same paired USB printer.
 * Only called when the order contains items from an area with imprimirComanda=true.
 */
export async function printComanda(data: ComandaData): Promise<void> {
	if (!device || !device.opened) {
		throw new Error('Impresora no configurada. Usa "Configurar Impresora" primero.');
	}

	const buffer = generateComanda(data);
	const endpointNumber = getOutEndpoint(device);

	const result = await device.transferOut(endpointNumber, buffer);

	if (result.status !== 'ok') {
		throw new Error(`Error al enviar comanda a la impresora (status: ${result.status}).`);
	}
}
